### ISSUE TITLE
Social Media Icons in Mobile

### ISSUE THREAD

**Issue by jose-duarte** [cogdog/wp-dimension#4]
Having issues with the social media icons when reduced to mobile screen size. Instead of keeping their order and line, which should be fine similar to your cog.dog website, it breaks into lines.

Example:
![screenshot_20181209-132032](https://user-images.githubusercontent.com/23359307/49697245-462ff300-fbb5-11e8-9816-c4a520697510.jpg)

In desktop:
![image](https://user-images.githubusercontent.com/23359307/49697263-62cc2b00-fbb5-11e8-8c30-13ff3ad448f7.png)

Any idea how to make it keep the original structure?

**Comment by cogdog** [comment]
Thanks for letting me know. I had an extra CSS class that was interfering with the proper layout, and causing the last icon in mobile view to have the wrong padding. If there are more than 2 icons, the mobile view will responsively stack them, but now they should be lined up, as on the [demo site](http://lab.cogdogblog.com/dimension/):

![mobile-menu](https://user-images.githubusercontent.com/463038/49704671-87d39480-fbdb-11e8-894c-335dfa982c2e.jpg)

Note that my personal site https://cog.dog actually uses the original static HTML theme the WordPress is based on, so is a little different. 

The fix is merely an update to `/assets/css/main/css` or the file at https://github.com/cogdog/wp-dimension/blob/master/assets/css/main.css Or you can just edit your own version of this file and remove lines 1661-1663

```
ul.actions li {
    padding: 0 2rem 0 0;
}
```
Sorry about that sloppy CSS! Please let me know if this takes care of the problem.

**Comment by jose-duarte** [comment]
That did it, thanks!
Chrome already pointed me in the direction of those lines but was not sure what to do, cheers.
