### ISSUE TITLE
Site not saving drafts or publishing front boxes?

### ISSUE THREAD

**Issue by jesslyndw** [cogdog/wp-dimension#5]
Hi @cogdog - I'm using Dimensions for the https://techforteaching.ca home page, but i can not for the life of me get it to save drafts or publish new front boxes.  I am just getting "Upditing Failed" or "Pubishing failed" error messages.  ![image](https://user-images.githubusercontent.com/53877196/62650431-e09f2c80-b924-11e9-97bc-36df874d5ae2.png)

I've tried:

- following all the recommended steps for [Wordpress updates](https://wordpress.org/support/topic/read-this-first-wordpress-5-0-master-list/)
- using the easy theme updater you've suggested, and reuploading the most recent version of the theme.

I'm not great with this. Any help you can offer is very much appreciated!
Jess

**Comment by cogdog** [comment]
That's not good. I cannot diagnose much. A few sites suggest clearing your web browser cache to solve problems with the WP 5 Gutenberg Editor. Others suggest installing the Classic Editor plugin.

I can only guess. If you want me to take a look, create an administrator account for me (under users) on your site. It will send me a password and let me login and poke around.

**Comment by jesslyndw** [comment]
Hey Alan,

Thank you for your help! I've tried a few of the suggestions below, they were on the Wordpress Support forum.  Any help you can offer is much appreciated.  I sent the new user registration to your email.

 If you find anything, I truly appreciate the help in advising on how I can fix it.  I don't remember doing something that should break it 🙁
Jesslyn Wilkinson
Educational Technology Officer - Teaching & Learning
Conestoga College Institute of Technology and Advanced Learning
299 Doon Valley Drive
Kitchener, ON
Office: 3A503

jwilkinson@conestogac.on.ca<mailto:jwilkinson@conestogac.on.ca>
519-748-5220 ext. 2531

Connect with Conestoga
________________________________

**Comment by cogdog** [comment]
There is some issue with the site setup that requires likely some tech support from Reclaim Hosting. 

When I go to create a new Post/Front Box, going into the Developer Console ([this is worth knowing how to do](https://www.lifewire.com/web-browser-developer-tools-3988965), I see errors reported a mix of loading content over https and http

![mixed-content](https://user-images.githubusercontent.com/463038/62672058-6a1b2280-b956-11e9-9baf-caf1831ceb4b.jpg)

I tried a few plugins that are supposed to help with these errors, but no fix. 

It's not a theme issue. You can tell because the error happens if you switch the theme; the same error occurs when creating  new post.

I can guess at things (maybe an issue with `.htaccess`), but it's best if you file a support ticket with Reclaim Hosting (do this inside your customer portal). I could do it for you butt is a good exercise. Let me know if you need more help explaining.
