### ISSUE TITLE
How to customize or replace or remove the white RETURN button that shows up on pages

### ISSUE THREAD

**Issue by sudhirmuw** [cogdog/wp-dimension#8]
Zero experience with doing anything with HTML or CSS. I’m using this theme and I was wondering if someone could walk me through (explain-like-I’m-5-style) on how to remove or replace or customize the “return” button that shows up at the bottom of each new page created with this theme. Is there a way to do this through the options WP gives me to edit pages or do I have to get into the CSS editor and remove it? And if I remove it, is there a repository of alternative buttons I can use in its place? Thanks!

**Comment by cogdog** [comment]
The return button was but there because there is no menu in this theme, so if you use a WordPress page, the only way a user can go anywhere is the browser back button. The theme was adapted meant to primarily use the front linking to posts, adding extra.

The return button could be hidden with CSS, not via the editor, but using the Customizer (Appearance -> Customize or from the admin menu while viewing the site, click Customize). and enter in the pane for **Additional CSS** 

```
type-page a.button.icon {
    display: none;
}
```

Making any changes to the button would requiring editing the `page.php` template, there is no editing of content that can do that or a button library. The icon is set by the CSS class `fa-hand-o-left` (the original template uses [old Font Awesome 4 icons](https://fontawesome.com/v4.7/icons/)). So you could get an arrow icon if you used `fa-arrow-left`

![arrow-left](https://user-images.githubusercontent.com/463038/129484796-67ae1510-0d43-4c5f-8130-19625d7a1472.jpg)

Or just remove the class completely to do icon

**Comment by sudhirmuw** [comment]
Thank you very much! Very helpful.
